SELECT s.WSTOCKID TRN_906446 ,s.SSTOCKCODE TRN_605 ,s.SDESCRIPTION TRN_1708 , sum(st.FQTY) TRN_960 ,st.WDOCTYPEID TRN_1869
FROM STOCKTRN st join stock s on s.WSTOCKID = st.WSTOCKID 
where  s.wstockTypeid <> 1 and 
<@DDATE@>
group by s.WSTOCKID,s.SSTOCKCODE,s.SDESCRIPTION, st.WDOCTYPEID
order by 2